# Generated by Django 4.2 on 2023-05-09 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photoapp', '0002_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='submitter',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='image',
        ),
        migrations.AddField(
            model_name='like',
            name='photo',
            field=models.ForeignKey(default='like', on_delete=django.db.models.deletion.CASCADE, to='photoapp.photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
