# Generated by Django 4.2 on 2023-05-11 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_rename_submitter_like_user_remove_like_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='likes',
        ),
    ]
